/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BattleShip.Game.PvP;

import BattleShip.Game.PvP.GameProcess.Game;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void sink_or_hit_ship_test() {

        char[][] battlefield = new char[10][10];

        for (char[] i : battlefield) {
            Arrays.fill(i, '~');
        }

        battlefield[0][0] = 'O';
        battlefield[0][1] = 'O';

        boolean actual1 = new Game().ship_is_up(battlefield, 'A', 1);

        assertTrue(actual1);

        boolean actual2 = new Game().ship_is_up(battlefield, 'A', 2);

        assertFalse(actual2);

    }

    @Test
    void win_condition_test() {

        char[][] battlefield = new char[10][10];

        battlefield[0][0] = 'O';

        boolean win = new Game().winCondition(battlefield);

        assertTrue(win);

    }

}
